CREATE DATABASE BD_PROYECTO

GO
USE BD_PROYECTO

GO
CREATE TABLE TB_USUARIO
(
  USU_COD BIGINT PRIMARY KEY IDENTITY,
  USU_NOM VARCHAR(255) DEFAULT NULL,
  USU_PASS VARCHAR(255) DEFAULT NULL,
  USU_EMAIL VARCHAR(255) DEFAULT NULL,  
  USU_CEL VARCHAR(255) DEFAULT NULL
)

GO
CREATE TABLE TB_ARTICULO
(
  ART_COD BIGINT PRIMARY KEY IDENTITY,
  ART_NOM VARCHAR(255) DEFAULT NULL,
  ART_DES VARCHAR(255) DEFAULT NULL,
  ART_PRE DECIMAL(18,2) DEFAULT NULL,
)

GO
CREATE TABLE TB_PEDIDO
(
  PED_COD BIGINT PRIMARY KEY IDENTITY,
  PED_USU_COD BIGINT NOT NULL FOREIGN KEY REFERENCES TB_USUARIO(USU_COD),
  PED_FEC VARCHAR(255) DEFAULT NULL,
  PED_DIR VARCHAR(255) DEFAULT NULL,
  PED_TOTAL DECIMAL(18,2) DEFAULT NULL
)

GO
CREATE TABLE TB_PEDIDO_DETALLE
(
  PDE_COD BIGINT PRIMARY KEY IDENTITY,
  PDE_PED_COD BIGINT NOT NULL FOREIGN KEY REFERENCES TB_PEDIDO(PED_COD),
  PDE_ART_COD BIGINT NOT NULL FOREIGN KEY REFERENCES TB_ARTICULO(ART_COD),
  PDE_PRE DECIMAL(18,2) DEFAULT NULL,
  PDE_CAN INT DEFAULT NULL,
  PDE_SUB DECIMAL(18,2) DEFAULT NULL
)
GO
CREATE TABLE TB_PEDIDO_SEGUIMIENTO
(
  PSE_COD BIGINT PRIMARY KEY IDENTITY,
  PSE_PED_COD BIGINT NOT NULL FOREIGN KEY REFERENCES TB_PEDIDO(PED_COD),
  PSE_FEC DATETIME NOT NULL,
  PSE_COR_LAT VARCHAR(255) NOT NULL,
  PSE_COR_LON VARCHAR(255) NOT NULL
)

INSERT INTO TB_USUARIO VALUES('USUARIO','123456','USUARIO@GMAIL.COM','987654321')

INSERT INTO TB_ARTICULO VALUES ('ARTICULO 01', 'DESCRIPCION', 1.50);
INSERT INTO TB_ARTICULO VALUES ('ARTICULO 02', 'DESCRIPCION', 3.50);

INSERT INTO TB_PEDIDO VALUES(1,'2017-02-12 00:32:55','DIRECCION',50.00)

INSERT INTO TB_PEDIDO_DETALLE VALUES(1,1,1.50,2,3.00)
INSERT INTO TB_PEDIDO_DETALLE VALUES(1,2,3.50,1,3.50)

INSERT INTO TB_PEDIDO_SEGUIMIENTO VALUES (1, '2017-02-12 00:32:55', -12.0948188,-77.0381757);
INSERT INTO TB_PEDIDO_SEGUIMIENTO VALUES (1, '2017-02-12 00:33:00', -12.0948188,-77.0381757);
INSERT INTO TB_PEDIDO_SEGUIMIENTO VALUES (1, '2017-02-12 00:32:55', -12.0948188,-77.0381757);
INSERT INTO TB_PEDIDO_SEGUIMIENTO VALUES (1, '2017-02-12 00:33:00', -12.0948188,-77.0381757);

GO
CREATE PROC USP_TB_USUARIO_INS
(
	@USU_NOM	VARCHAR(255),
	@USU_PASS	VARCHAR(255),
	@USU_EMAIL	VARCHAR(255),  
	@USU_CEL	VARCHAR(255)
)
AS
BEGIN

	IF NOT EXISTS(SELECT 1 FROM TB_USUARIO WHERE USU_NOM=@USU_NOM)
	BEGIN
		INSERT INTO TB_USUARIO (USU_NOM,USU_PASS,USU_EMAIL,USU_CEL)
		VALUES(@USU_NOM,@USU_PASS,@USU_EMAIL,@USU_CEL)
		SELECT 1
	END
	ELSE
	BEGIN
		SELECT 0
	END
END

GO
CREATE PROC USP_TB_USUARIO_SEL
(
	@USU_NOM	VARCHAR(255)
)
AS
BEGIN
	SELECT USU_COD,USU_NOM,USU_PASS,USU_EMAIL,USU_CEL 
	FROM TB_USUARIO WHERE RTRIM(LTRIM(USU_NOM))=RTRIM(LTRIM(@USU_NOM))
END

GO
CREATE PROC USP_TB_ARTICULO_INS
(
	@ART_NOM	VARCHAR(255),
	@ART_DES	VARCHAR(255),
	@ART_PRE	DECIMAL(18,2)
)
AS
BEGIN

	IF NOT EXISTS(SELECT 1 FROM TB_ARTICULO WHERE ART_NOM=@ART_NOM)
	BEGIN
		INSERT INTO TB_ARTICULO (ART_NOM,ART_DES,ART_PRE)
		VALUES(@ART_NOM,@ART_DES,@ART_PRE)
		SELECT 1
	END
	ELSE
	BEGIN
		SELECT 0
	END
END

GO
CREATE PROC USP_TB_ARTICULO_SEL
AS
BEGIN
	SELECT ART_COD,ART_NOM,ART_DES,ART_PRE 
	FROM TB_ARTICULO
END


GO
CREATE PROC USP_TB_PEDIDO_INS
(
	@PED_USU_COD BIGINT,
	@PED_DIR VARCHAR(255)
)
AS
BEGIN
	INSERT INTO TB_PEDIDO (PED_USU_COD,PED_FEC,PED_DIR)
	VALUES (@PED_USU_COD,GETDATE(),@PED_DIR)
	
	SELECT CAST(SCOPE_IDENTITY() AS BIGINT)
END

GO
CREATE PROC USP_TB_PEDIDO_DETALLE_INS
(
	@PDE_PED_COD BIGINT,
	@PDE_ART_COD BIGINT,
	@PDE_CAN INT
)
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM TB_PEDIDO_DETALLE WHERE PDE_PED_COD=@PDE_PED_COD AND PDE_ART_COD=@PDE_ART_COD)
	BEGIN
		INSERT INTO TB_PEDIDO_DETALLE (PDE_PED_COD,PDE_ART_COD,PDE_PRE,PDE_CAN,PDE_SUB)
		SELECT @PDE_PED_COD,@PDE_ART_COD,ART_PRE,@PDE_CAN,ART_PRE*@PDE_CAN
		FROM TB_ARTICULO WHERE ART_COD=@PDE_ART_COD
	END
	ELSE
	BEGIN
		UPDATE TMP
		SET TMP.PDE_CAN=TMP.PDE_CAN+@PDE_CAN
			,TMP.PDE_SUB=TMP.PDE_SUB+(A.ART_PRE*@PDE_CAN)
		FROM TB_PEDIDO_DETALLE TMP
		INNER JOIN TB_ARTICULO A ON A.ART_COD=TMP.PDE_ART_COD AND A.ART_COD=@PDE_ART_COD
		WHERE TMP.PDE_PED_COD=@PDE_PED_COD
	END
	
	UPDATE TMP
	SET TMP.PED_TOTAL=(SELECT SUM(PDE_SUB) FROM TB_PEDIDO_DETALLE WHERE PDE_PED_COD=@PDE_PED_COD)
	FROM TB_PEDIDO TMP
	WHERE TMP.PED_COD=@PDE_PED_COD
	
	SELECT 1
END


GO
CREATE PROC USP_TB_PEDIDO_SEGUIMIENTO_INS
(
	@PSE_PED_COD BIGINT,
	@PSE_COR_LAT VARCHAR(255),
	@PSE_COR_LON VARCHAR(255)
)
AS
BEGIN
	INSERT INTO TB_PEDIDO_SEGUIMIENTO(PSE_PED_COD,PSE_FEC,PSE_COR_LAT,PSE_COR_LON)
	VALUES(@PSE_PED_COD,GETDATE(),@PSE_COR_LAT,@PSE_COR_LON)	
END

GO
CREATE PROC USP_TB_PEDIDO_USUARIO_SEL
(
	@PED_USU_COD BIGINT
)
AS
BEGIN
	SELECT PED_COD,PED_FEC,PED_DIR,PED_TOTAL FROM TB_PEDIDO
	WHERE PED_USU_COD=@PED_USU_COD
END

GO
CREATE PROC USP_TB_PEDIDO_DETALLE_SEL
(
	@PDE_PED_COD BIGINT
)
AS
BEGIN
	SELECT ART_NOM,ART_DES,PDE_PRE,PDE_CAN,PDE_SUB
	FROM TB_PEDIDO_DETALLE PD
	INNER JOIN TB_ARTICULO A ON A.ART_COD=PDE_ART_COD
	WHERE PD.PDE_PED_COD=@PDE_PED_COD
END

GO
CREATE PROC USP_TB_PEDIDO_SEGUIMIENTO_SEL
(
	@PSE_PED_COD BIGINT
)
AS
BEGIN
	SELECT PSE_FEC,PSE_COR_LAT,PSE_COR_LON
	FROM TB_PEDIDO_SEGUIMIENTO
	WHERE PSE_PED_COD=@PSE_PED_COD
END